# CircleCI YAML docs
# https://circleci.com/docs/2.0/writing-yaml/#section=configuration

version: 2

jobs:
    build:
        macos:
            xcode: "10.2.0"
        steps:
            - checkout

            - run: 
                name: Install Fastlane dependencies
                command: cd Branch-TestBed && bundle install
            
            - run:
                name: Fetch CocoaPods Specs
                command: |
                    curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
            - run:
                name: Install CocoaPod dependencies
                command: cd Branch-TestBed && pod install --verbose

            - run:
                name: Install Apple certificates using Fastlane Match
                command: cd Branch-TestBed && bundle exec fastlane match
                
            - run:
                name: Unit tests
                command: xcodebuild test -workspace Branch-TestBed/Branch-TestBed.xcworkspace -scheme Branch-SDK-Unhosted-Tests -destination 'platform=iOS Simulator,name=iPhone X,OS=12.2'
                
            - run:
                name: Integration tests
                command: xcodebuild test -workspace Branch-TestBed/Branch-TestBed.xcworkspace -scheme Branch-SDK-Tests -destination 'platform=iOS Simulator,name=iPhone X,OS=12.2'
